//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTAWEB.Models.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class NEWS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NEWS()
        {
            this.PICTUREs = new HashSet<PICTURE>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string picture { get; set; }
        public string content { get; set; }
        public string detail { get; set; }
        public Nullable<bool> avtive { get; set; }
        public Nullable<System.DateTime> dateup { get; set; }
        public string tacgia { get; set; }
        public Nullable<int> nguoidang { get; set; }
        public Nullable<int> idSubCategory { get; set; }
        public Nullable<int> idUnitCategory { get; set; }
    
        public virtual ADMIN ADMIN { get; set; }
        public virtual SUBCATEGOTY SUBCATEGOTY { get; set; }
        public virtual UNITCATEGOTY UNITCATEGOTY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PICTURE> PICTUREs { get; set; }
    }
}
