//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTAWEB.Models.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class PICTURE
    {
        public int idPicture { get; set; }
        public string linkPicture { get; set; }
        public Nullable<int> idNews { get; set; }
    
        public virtual NEWS NEWS { get; set; }
    }
}
