//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTAWEB.Models.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNITCATEGOTY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UNITCATEGOTY()
        {
            this.NEWS = new HashSet<NEWS>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> lever { get; set; }
        public Nullable<int> idSubCategory { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NEWS> NEWS { get; set; }
        public virtual SUBCATEGOTY SUBCATEGOTY { get; set; }
    }
}
